# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports: 
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  fastify: 
    image: 503424096631.dkr.ecr.ap-northeast-2.amazonaws.com/project2-container-repo:32726d372a4597cd416c598803f21dd0d8259993
    restart: always
    ports: 
      - '3000:3000'
    depends_on:
    - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOSTNAME: mongo
