name: Node.js CI

on:
  push:
    branches: [ "JEONGDratini" ]
  pull_request:
    branches: [ "JEONGDratini" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install tap --save-dev
    - run: npm test
