name: Push Registry

on:
  push:
    branches:
      - JEONGDratini2

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          aws-access-key-id: ${{ secrets.ROMENCIA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ROMENCIA_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ROMENCIA_ECR_REGISTRY}}/project2-container-repo/project2-container-repo:${{ github.sha }}

